### ISSUE TITLE
Encapsulate the file tree (not the entire sidebar!) into a directive+controller+template

### ISSUE THREAD

**Issue by Thatkookooguy** [Kibibit/kibibit-code-editor#35]
we have the sidebar component and the file tree component.

Here's a little overview of what we plan to do:

>kibibit
>>menu bar
>>
>>Sidebar
>>>**file-tree**
>>>file-overview (for example)
>>
>>tabs-container
>>>tab[i]
>>>>code-editor **OR** diff **OR** ungit **OR** markdown **OR** ...

This mission it to encapsulate the file tree **only**.

# Requirements
1. Should accept a path via an attribute and load it as a tree.
2. Should be 100% width and height of it's container. This is to allow the parent component (the sidebar) to reduce the height by reducing the height of its container in order to include a second view in the sidebar + in order to be responsive when sidebar is resized.

**Comment by Thatkookooguy** [comment]
part of #21

**Comment by ortichon** [comment]
@Thatkookooguy 
Hi, 
how would you like me to implement binding of the received data from FileService to the main.code variable (in mainCtrl) ?
up until now the fileTree functionality was in mainCtrl, so binding was no problem.

for testing purposes I used $rootScope event in order to comunicate between those Ctrls, but please let me know how you want it to be.
